### ISSUE TITLE
App Center - Execution failed for task ':react-native-mmkv-storage:generateJsonModelRelease'. 

### ISSUE THREAD

**Issue by amk-cb** [ammarahm-ed/react-native-mmkv-storage#160]
Execution failed for task ':react-native-mmkv-storage:generateJsonModelRelease'.
> /Users/runner/work/1/s/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv/CMakeLists.txt : C/C++ release|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  REACT_NATIVE_JNI_LIB
      linked by target "rnmmkv" in directory /Users/runner/work/1/s/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv
  REACT_NATIVE_UTILS_LIB
      linked by target "rnmmkv" in directory /Users/runner/work/1/s/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv

**Comment by ammarahm-ed** [comment]
See closed issues for fixing this

**Comment by amk-cb** [comment]
i have seen but they are for  `java.lang.NullPointerException `.
and here it is showing `CMake Error`

if i am wrong please share the correct link.

**Comment by amk-cb** [comment]
earlier i followed this [issue](https://github.com/ammarahm-ed/react-native-mmkv-storage/issues/132), and  ` java.lang.NullPointerException ` worked fine.
but from some days this new issues is coming up and i am stucked in it.
Please help me out.

**Comment by amq** [comment]
In my case, it only complains about `REACT_NATIVE_UTILS_LIB`

I can find:
```
node_modules\react-native-mmkv-storage\android\build\react-native-0.63.4.aar\jni\armeabi-v7a\libreactnativejni.so
```

But this file doesn't exist, and that's probably the cause for the problem:
```
node_modules\react-native-mmkv-storage\android\build\react-native-0.63.4.aar\jni\armeabi-v7a\lib\reactnativeutilsjni.so
```

(0.6.1)

**Comment by amq** [comment]
Seems like on react-native 0.63 it's called reactnativejni:

https://github.com/facebook/react-native/blob/27651720b40cab564a0cbd41be56a02584e0c73a/ReactAndroid/src/main/jni/react/jni/Android.mk#L34

While on 0.64+ it's reactnativeutilsjni:

https://github.com/facebook/react-native/blob/757bb75fbf837714725d7b2af62149e8e2a7ee51/ReactAndroid/src/main/jni/react/jni/Android.mk#L39

**Comment by amk-cb** [comment]
I am on "react-native": "0.64.1", may be that's why i am getting both.

and @amq how did you fix that first complaint.

**Comment by ammarahm-ed** [comment]
@amk-cb @amq I am working on a fix.

**Comment by amk-cb** [comment]
@ammarahm-ed  Thank you very much :). I appreciate your work.

**Comment by ammarahm-ed** [comment]
@amk-cb can you try now by adding master branch and testing?

```
yarn add https://github.com/ammarahm-ed/react-native-mmkv-storage.git
```

**Comment by amk-cb** [comment]
i tried but same error.

**Comment by ammarahm-ed** [comment]
@amk-cb are you getting the same error on building locally?

**Comment by amk-cb** [comment]
on app center

**Comment by ammarahm-ed** [comment]
Well you need to figure this out. I don't have app center access. it is probably related to paths in build.gradle file of the library that searches for react native libs. It is unable to find those libraries and hence the build is failing. Try stack overflow. 

I have a github action here which is building android app normally so something must  be up with app center configuration

**Comment by hieuhoit** [comment]
the same issue on app circle :(

**Comment by kutaisan** [comment]
same error on app center.

**Comment by ammarahm-ed** [comment]
@kutaisan I am trying to debug it but unless it can be reproduced locally it is hard to debug. here is the cloud build machine setup for app center: https://docs.microsoft.com/en-us/appcenter/build/software

You can see the cmake version, sdk and ndk version it using. 

ndk 

```
15.2.4203891
18.1.5063045
21.4.7075529
22.1.7171670
```
cmake:
```
3.10.2
3.18.1
```
cmake installed globally: 
```
3.21.2
```

A way to debug is to setup a similar or closest environment and trying to build.

**Comment by ammarahm-ed** [comment]
This issue is fixed. I was able to build successfully in app center after debugging for a few hours.

**Comment by kutaisan** [comment]
> This issue is fixed. I was able to build successfully in app center after debugging for a few hours.

Is there any update for fix?

**Comment by ammarahm-ed** [comment]
@kutaisan  wait a few minutes

**Comment by ammarahm-ed** [comment]
@kutaisan @amk-cb  @amq Try now. First add react-native-mmkv-storage in your project then push to master then build it in app center.

```
yarn add https://github.com/ammarahm-ed/react-native-mmkv-storage.git
```

**Comment by amk-cb** [comment]
ok @ammarahm-ed

**Comment by ammarahm-ed** [comment]
Do let me know so i can close the issue and make a new release on npm. Here is the  example app building successfully on App Center.

![Screenshot from 2021-09-20 21-30-35](https://user-images.githubusercontent.com/40239442/134039154-92b634ff-aa09-4cbe-bf18-d17852590076.png)

**Comment by amk-cb** [comment]
@ammarahm-ed  now error is reduced to this,

Execution failed for task ':react-native-mmkv-storage:generateJsonModelRelease'.
> /Users/runner/work/1/s/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv/CMakeLists.txt : C/C++ release|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  REACT_NATIVE_JNI_LIB
      linked by target "rnmmkv" in directory /Users/runner/work/1/s/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv

**Comment by ammarahm-ed** [comment]
That's the error I fixed. The example app is building on App Center. @amk-cb Are you sure you added the library using the above command? Share your build logs here from app center.

The example app is on RN 0.65.1 but it should still build on older versions too. 

Also try running debug build instead of release on App Center. See if that is passing.

**Comment by amk-cb** [comment]
yes i ran that command,
    `"react-native": "0.64.1",`
    `"react-native-mmkv-storage": "https://github.com/ammarahm-ed/react-native-mmkv-storage.git",`

**Comment by amk-cb** [comment]
@ammarahm-ed  debug is building successfully.

But release is failing

**Comment by hieuhoit** [comment]
on Appcircle, in my case:

```
> Task :react-native-mmkv-storage:generateJsonModelRelease FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
619 actionable tasks: 589 executed, 30 up-to-date
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':react-native-mmkv-storage:generateJsonModelRelease'.
> .../_appcircle_temp/Repository/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv/CMakeLists.txt : C/C++ release|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  REACT_NATIVE_JNI_LIB
      linked by target "rnmmkv" in directory .../_appcircle_temp/Repository/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv
  REACT_NATIVE_UTILS_LIB
      linked by target "rnmmkv" in directory .../_appcircle_temp/Repository/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv

```

**Comment by bitcrumb** [comment]
On our Gitlab instance we're seeing failure with the 0.6.1 release as well. Downgrading to 0.6.0 fixes the issue.

**Comment by ammarahm-ed** [comment]
I think I have fixed it for release too.

**Comment by ammarahm-ed** [comment]
Alright It's fixed now for release and debug both. Try by installing master branch in your project. Push to git then build in App Center/ App Circle or Gitlab etc.

```
yarn add https://github.com/ammarahm-ed/react-native-mmkv-storage.git
```
@amk-cb @bitcrumb @hieuhoit 

If it builds fine let me know. The example app is building on App Center in release and debug without issues.

![Screenshot from 2021-09-21 00-12-24](https://user-images.githubusercontent.com/40239442/134060673-480abcef-f5db-4f28-aef1-4a1e1429af58.png)

**Comment by amk-cb** [comment]
Release passed. 

awesome work @ammarahm-ed bro.
Thank you so much..

**Comment by ammarahm-ed** [comment]
Released `v0.6.3` on npm

**Comment by bitcrumb** [comment]
@ammarahm-ed I only got around to testing it now. But I'm still seeing an error related to JNI:

```
> Task :app:mergeUnifiedClientreleaseNativeLibs FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:mergeUnifiedClientreleaseNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'lib/x86_64/libreactnativejni.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake
```

The link in the error above is not entirely correct anymore, this is the working link:
https://developer.android.com/studio/releases/gradle-plugin#cmake-imported-targets

Doest that ring a bell? Is this something this library has to fix, or could this have to do with my setup?

> Prior versions of the Android Gradle Plugin required that you explicitly package any prebuilt libraries used by your CMake external native build by using jniLibs. You may have libraries in the src/main/jniLibs directory of your module, or possibly in some other directory configured in your build.gradle file:
> ...
> With Android Gradle Plugin 4.0, the above configuration is no longer necessary and will result in a build failure:
> ...
> External native build now automatically packages those libraries, so explicitly packaging the library with jniLibs results in a duplicate. To avoid the build error, move the prebuilt library to a location outside jniLibs or remove the jniLibs configuration from your build.gradle file.

**Comment by ammarahm-ed** [comment]
@bitcrumb try adding the following in your app/build.gradle and it should build properly.

```
packagingOptions {
    pickFirst '**/*.so'
}
```
I am unsure to why this error is being thrown. The example app is on RN 0.65.1 and it builds fine. No issues. The current error is just that two different libraries and building the same .so file and putting it in native libs when building the app. The above should be able to fix this.

**Comment by bitcrumb** [comment]
Thanks for your swift response! I'll give it a try :)

**Comment by bitcrumb** [comment]
@ammarahm-ed The "funny" thing is, when I run the build locally I don't get this error. Only when running the build on our Gitlab instance.

Still seems like `react-native-mmkv-storage` is including certain c++ the wrong way, leading gradle to detect duplicate includes?

Feels like a workaround/hack to have to include this "pickFirst" strategy?

(still awaiting build result on Gitlab btw)

**Comment by bitcrumb** [comment]
A'ight. Your suggestion worked! Thanks for that :)
I'll leave it up to you to decide if this is something that needs to be addressed further or not. Thanks again 👍🏻

**Comment by ammarahm-ed** [comment]
@bitcrumb I will investigate this. The above is a pretty standard way to resolve this problem when multiple libraries build the same .so file. It doesn't happen in the example app. One way would be to exclude it after the library builds during the build process. I will test.

**Comment by hieuhoit** [comment]
now it fail on debug :(

```
> Task :react-native-mmkv-storage:generateJsonModelDebug FAILED
Execution failed for task ':react-native-mmkv-storage:generateJsonModelDebug'.
> /Volumes/Data/Hie/ReactNative/Soteria/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  REACT_NATIVE_JNI_LIB
      linked by target "rnmmkv" in directory /Volumes/Data/Hie/ReactNative/Soteria/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by ammarahm-ed** [comment]
Not sure how you have configured. The example app builds fine on Appcenter in debug and release mode.

**Comment by hieuhoit** [comment]
just happen after rebuild on Android Studio
