### ISSUE TITLE
[Bug?] useMMKVStorage hook with prevState parameter is null on first run (no values in storage)

### ISSUE THREAD

**Issue by maarten-22** [ammarahm-ed/react-native-mmkv-storage#202]
**Describe the bug**
It seems like `prevState` is not set to the default value passed to `useMMKVStorage` hook. Only happens on the first run when there haven't been any values set. Example:
**Expected behavior**
```js
const [stateObject, setStateObject] = useState({ enabled: true, for: 'id-123'});

const handleState = () => {
   setStateObject((prevState) => {
      console.log(prevState) // { enabled: true, for: 'id-123'}
   })
}
```

**Actual behavior**
```js
// useStorage == wrapper for useMMKVStorage like in docs
const [stateObject, setStateObject] = useStorage('KEY', { enabled: true, for: 'id-123'});

const handleState = () => {
   setStateObject((prevState) => {
      console.log(prevState) // null - we want default object
   })
}
```

**Possible fix**
I am not sure about the implementation behind useMMKVStorage, but this seems to be caused by `getInitialValue` in `functions.js`.
```js
export const getInitialValue =
  ({ key,storage,kindValue }) =>
  () => {
    if (!storage?.indexer) {
      return null;
    }
    let indexer = storage.indexer;
    if (indexer.hasKey(key)) {
      for (let i = 0; i < types.length; i++) {
        let type = types[i];
        if (indexer[methods[type].indexer].hasKey(key)) {
          if (kindValue === "value") {
            return storage[methods[type]["get"]](key);
          }
          if (kindValue === "valueType") {
            return type;
          }
        }
      }
    }
    return null; // <-- HERE?
  };
```

Passing `defaultValue` into here instead of `null` would result in the object getting returned. Like this:
```js
export const getInitialValue =
  ({ key,storage,kindValue, defaultValue }) =>
  () => {
    if (!storage?.indexer) {
      return null;
    }
    let indexer = storage.indexer;
    if (indexer.hasKey(key)) {
      for (let i = 0; i < types.length; i++) {
        let type = types[i];
        if (indexer[methods[type].indexer].hasKey(key)) {
          if (kindValue === "value") {
            return storage[methods[type]["get"]](key);
          }
          if (kindValue === "valueType") {
            return type;
          }
        }
      }
    }
    return defaultValue;
  };
```

I am not sure if this causes any side effects. You would know this best. If it's okay I can open a pull request with the changes.

**Comment by maarten-22** [comment]
As a temporary fix you can do this:
```js
setObjectState((prevState) => {
   if (prevState === null) return { ...stateObject, enabled: !stateObject.enabled }
   return { ...prevState, enabled: !prevState.enabled }
})
```

**Comment by ammarahm-ed** [comment]
@aLemonFox You are right. The fix is simple. Just needed to pass `defaultValue` as param if `value` is null in `nextValue` function.

```js
updatedValue = nextValue(prevValue.current || defaultValue);
```
 I have fixed it on master. Give it a try.
```
yarn add https://github.com/ammarahm-ed/react-native-mmkv-storage.git
```
Let me know if it works as expected so I can push a new release

**Comment by ammarahm-ed** [comment]
@aLemonFox You are right. The fix is simple. Just needed to pass `defaultValue` as param if `value` is null in `nextValue` function.

```js
updatedValue = nextValue(prevValue.current || defaultValue);
```
 I have fixed it on master. Give it a try.
```
yarn add https://github.com/ammarahm-ed/react-native-mmkv-storage.git
```
Let me know if it works as expected so I can push a new release

**Comment by maarten-22** [comment]
Perfect, it seems to work fine now.
This was actually related to my previous issue: https://github.com/ammarahm-ed/react-native-mmkv-storage/issues/201#issue-1100146074
But since I was inverting `null`, I'd still get `true` however the underlying code would break because it was looking for strict false `=== false`
